<?php
// This is the template for the infonotice
/**
 * @var Mastering\SampleModule\Block\InfoNotice $block
 */

// Gets the data for placing
$infoNoticeMessage = $block->getConfigurationData();
// if there is an info notice, and it is set to enabled then show it on the page
if($infoNoticeMessage != false){
?>
    <div class="info-notice" style="text-align:center">
        <?php
        for($i = 0; $i < strlen($infoNoticeMessage); $i++){
            if($i%2 == 0){
                echo '<span class="green-letter">' . $infoNoticeMessage[$i] . '</span>';
            }else{
                echo '<span class="red-letter">' . $infoNoticeMessage[$i]. '</span>';
            }
        }
        ?>
    </div>
<?php
}